[package]
name = "sdev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.clap]
version = "3"
default-features = false
features = ["std", "derive", "unstable-v4"]
